gaussian elimination
1. find pivot element --> first non-zero element in current column that hasn't been eliminated
2. swap rows: If the pivot element is zero, swap with a lower row that has a non-zero element in the current column
to avoid division by zero
3. normalize: divide entire row by pivot element
4. Subtract a suitable multiple of the pivot row from all the rows below it to make all elements below the
pivot equal to zero in the current column
5. repeat for all rows
6. solve for each variable


In [2]:
import numpy as np
def gaussian_elimination(A, b):
    n = len(b)
    # Forward elimination
    for i in range(n):
        # Pivoting
        max_row = max(range(i, n), key=lambda x: abs(A[x][i]))
        A[i], A[max_row] = A[max_row], A[i]
        b[i], b[max_row] = b[max_row], b[i]
        # Make the rows below this one 0 in current column
        for j in range(i + 1, n):
            ratio = A[j][i] / A[i][i]
            A[j] = [A[j][k] - ratio * A[i][k] for k in range(n)]
            b[j] -= ratio * b[i]
    # Backward substitution
    x = [0] * n
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - sum(A[i][j] * x[j] for j in range(i + 1, n))) / A[i][i]
    return x

In [3]:
# Example Usage
A = [[2,3,-1], [4,-2,2], [-2,1,2]]
b = [5,6,1]
solution = gaussian_elimination(A, b)
print(f"Solution: {solution}")

Solution: [1.4166666666666665, 1.1666666666666665, 1.3333333333333333]


In [5]:
ans = np.linalg.solve(A,b) # does the same thing
print(ans)

[1.41666667 1.16666667 1.33333333]


LU Decomposition
factoring a matrix A into two other matrices that are easier to solve (lower triangular L and upper triangular U)
A = LU
L --> lower triangular: all zeros above the diagonal
U --> upper triangular: all zeros below the diagonal
lets you solve Ax = b much faster than gaussian elimination

1. Decompose Matrix A into L and U:
○ Start with the first element and create zeros below the main diagonal in each column.
○ Proceed column by column, eliminating elements below the diagonal while forming L and U.
2. Solve the System:
○ For Ax=b, solve Ly=b using forward substitution.
○ Then solve Ux=y using backward substitution.

identity matrix: matrix with the diagonal as 1


In [6]:
def lu_decomposition(A):
    n = len(A)
    L = np.eye(n) # Initialize L as an identity matrix
    U = np.array(A, dtype=float) # Copy of A to avoid
    # modifying the original matrix
    # modifying the original matrix
    for i in range(n):
        # Eliminate elements below the pivot (U[i, i])
        for j in range(i+1, n):
            if U[i, i] == 0:
                raise ValueError("Zero pivot encountered. LU decomposition cannot proceed.")
        factor = U[j, i] / U[i, i] # Multiplier for row
        # operation
        L[j, i] = factor # Store multiplier in L
        # Update the rows of U
        for k in range(i, n):
            U[j, k] -= factor * U[i, k]
    return L, U


In [7]:
# Example usage
A = np.array([[2, 3, 1],
[4, 7, -1],
[-2, 1, 2]])
L, U = lu_decomposition(A)
print("Matrix A:\n", A)
print("Lower Triangular Matrix L:\n", L)
print("Upper Triangular Matrix U:\n", U)


Matrix A:
 [[ 2  3  1]
 [ 4  7 -1]
 [-2  1  2]]
Lower Triangular Matrix L:
 [[ 1.          0.          0.        ]
 [ 0.          1.          0.        ]
 [-1.          0.57142857  1.        ]]
Upper Triangular Matrix U:
 [[ 2.  3.  1.]
 [ 4.  7. -1.]
 [ 0.  0.  0.]]


In [10]:
from scipy.linalg import lu
P,L,U = lu(A)
print(A,"\n")
print(L,"\n")
print(U,"\n")

[[ 2  3  1]
 [ 4  7 -1]
 [-2  1  2]] 

[[ 1.          0.          0.        ]
 [-0.5         1.          0.        ]
 [ 0.5        -0.11111111  1.        ]] 

[[ 4.          7.         -1.        ]
 [ 0.          4.5         1.5       ]
 [ 0.          0.          1.66666667]] 



there are problems that you can't solve with these methods

iterative methods:
taking a guess, refine step by step
trying to get matrices to be diagonally dominant so you can approximate the answers

Jacobi and Gauss-Seidel
