In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
v1 = np.array([1,2,3]) # making a vector, 3 dimensional
v2 = np.array([4,5,6])

In [3]:
print(v1,v2)

[1 2 3] [4 5 6]


In [4]:
vAdd = v1+v2
vSub = v2-v1

In [5]:
print(vAdd,vSub)

[5 7 9] [3 3 3]


In [6]:
vScaled = 2*v1

In [7]:
print(vScaled)

[2 4 6]


In [8]:
vDot = np.dot(v1,v2)
magnitude_v1 = np.linalg.norm(v1)

In [9]:
print(magnitude_v1)

3.7416573867739413


In [10]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8,9],[10,11,12],[13,14,15]])

print(A)
print(B)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [11]:
C = np.array([[1,2,3],[4,5,6]])
mAdd = A+C
mSub = A-C

In [12]:
print(mAdd)
print(mSub)

[[ 2  4  6]
 [ 8 10 12]]
[[0 0 0]
 [0 0 0]]


In [13]:
matrixMul = np.dot(A.T,C)

In [14]:
# Coefficient matrix A and constant vector b
A = np.array([[2, 3], [4, -1]])
b = np.array([5, 3])
# Solve the system A * x = b
x = np.linalg.solve(A, b)
print("Solution (x, y):", x)


Solution (x, y): [1. 1.]


### eigenvalues and eigenvectors
for a square matrix A, there exists a lambda and a vector v such that Av = lambda*v
- eigenvectors are directions tha tdon't change when a matrix acts on them
- eigenvalues tell you how much stretch those directions have (negative = decay, positive = growth, complex = oscillations






In [15]:
A = np.array([[2,1],[1,2]])
eigenvalue, eigenvectors = np.linalg.eig(A)

In [16]:
print(eigenvalue, eigenvectors)

[3. 1.] [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


#### inverse of a matrix
A^-1 = i

In [17]:
A = np.array([[4, 7], [2, 6]])
A_inv = np.linalg.inv(A)


In [18]:
identity = np.dot(A, A_inv)

print(A_inv)
print(identity)

[[ 0.6 -0.7]
 [-0.2  0.4]]
[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


#### singular value decomposition
Singular Value Decomposition (SVD) is a factorization of a matrix into three
matrices:
A=UΣV T
Where:

● U and V are orthogonal matrices,

● Σ is a diagonal matrix of singular values

In [19]:
# Define a matrix
A = np.array([[1, 2], [3, 4], [5, 6]])
# Perform SVD
U, sigma, Vt = np.linalg.svd(A)
print("U matrix:\n", U)
print("Sigma values:", sigma)
print("V^T matrix:\n", Vt)

U matrix:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Sigma values: [9.52551809 0.51430058]
V^T matrix:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
